# Generated by Django 5.0.6 on 2024-06-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_description_remove_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
