# Generated by Django 5.0.6 on 2024-07-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_bloodtype_item_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='citizenship',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='philhealth_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
