# Generated by Django 5.0.6 on 2024-07-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_citizenship_item_philhealth_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='school_year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
