# Generated by Django 5.0.6 on 2024-07-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_item_school_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='school_year',
            new_name='college_SY',
        ),
        migrations.AddField(
            model_name='item',
            name='elementary_SY',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='highschool_SY',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vocational_SY',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
