# Generated by Django 5.0.6 on 2024-07-07 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_school_year_item_college_sy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='college_SY',
            new_name='college_sy',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='elementary_SY',
            new_name='elementary_sy',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='highschool_SY',
            new_name='highschool_sy',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='vocational_SY',
            new_name='vocational_sy',
        ),
    ]
